create extension if not exists pgcrypto;

create table users (
    id bigint generated by default as identity primary key,
    username text not null,
    normalized_username text not null,
    password_hash text not null,
    role text not null check (role in ('admin', 'viewer')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index users_normalized_username_key
    on users (normalized_username);

create table sessions (
    id uuid primary key default gen_random_uuid(),
    user_id bigint not null references users (id) on delete cascade,
    created_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    expires_at timestamptz not null,
    ip_address inet,
    user_agent text
);

create index sessions_user_id_idx
    on sessions (user_id);

create index sessions_expires_at_idx
    on sessions (expires_at);

create table images (
    id bigint generated by default as identity primary key,
    sha256 char(64) not null,
    original_path text not null,
    preview_path text not null,
    thumbnail_path text not null,
    original_filename text not null,
    mime_type text not null,
    width integer not null check (width > 0),
    height integer not null check (height > 0),
    file_size bigint not null check (file_size >= 0),
    rating text not null check (rating in ('safe', 'suggestive', 'explicit')),
    source_url text,
    note text,
    imported_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index images_sha256_key
    on images (sha256);

create index images_imported_at_id_idx
    on images (imported_at, id);

create index images_original_filename_id_idx
    on images ((lower(original_filename)), id);

create table tags (
    id bigint generated by default as identity primary key,
    namespace text not null,
    name text not null,
    normalized_namespace text not null,
    normalized_name text not null,
    created_at timestamptz not null default now()
);

create unique index tags_normalized_namespace_name_key
    on tags (normalized_namespace, normalized_name);

create index tags_namespace_name_idx
    on tags (namespace, name);

create index tags_normalized_name_prefix_idx
    on tags (normalized_name text_pattern_ops);

create table image_tags (
    image_id bigint not null references images (id) on delete cascade,
    tag_id bigint not null references tags (id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (image_id, tag_id)
);

create index image_tags_tag_id_image_id_idx
    on image_tags (tag_id, image_id);

create table favorites (
    user_id bigint not null references users (id) on delete cascade,
    image_id bigint not null references images (id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, image_id)
);

create table import_jobs (
    id uuid primary key default gen_random_uuid(),
    created_by_user_id bigint references users (id) on delete set null,
    source_filename text not null,
    source_archive_path text not null,
    status text not null check (
        status in ('queued', 'running', 'completed', 'completed_with_errors', 'failed')
    ),
    total_items integer not null default 0 check (total_items >= 0),
    processed_items integer not null default 0 check (processed_items >= 0),
    succeeded_items integer not null default 0 check (succeeded_items >= 0),
    failed_items integer not null default 0 check (failed_items >= 0),
    attempt_count integer not null default 0 check (attempt_count >= 0),
    available_at timestamptz not null default now(),
    heartbeat_at timestamptz,
    started_at timestamptz,
    finished_at timestamptz,
    last_error text,
    payload_json jsonb not null default '{}'::jsonb,
    result_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index import_jobs_status_available_at_idx
    on import_jobs (status, available_at, created_at);

create table download_jobs (
    id uuid primary key default gen_random_uuid(),
    requested_by_user_id bigint references users (id) on delete set null,
    status text not null check (
        status in ('queued', 'running', 'completed', 'failed', 'expired')
    ),
    total_items integer not null default 0 check (total_items >= 0),
    estimated_total_bytes bigint not null default 0 check (estimated_total_bytes >= 0),
    archive_path text,
    archive_size bigint check (archive_size is null or archive_size >= 0),
    expires_at timestamptz,
    attempt_count integer not null default 0 check (attempt_count >= 0),
    available_at timestamptz not null default now(),
    heartbeat_at timestamptz,
    started_at timestamptz,
    finished_at timestamptz,
    last_error text,
    selection_json jsonb not null default '[]'::jsonb,
    result_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index download_jobs_status_available_at_idx
    on download_jobs (status, available_at, created_at);

create index download_jobs_expires_at_idx
    on download_jobs (expires_at);
